language: python
matrix:
  include:
  - python: 3.5
    dist: trusty
    sudo: false
  - python: 3.6
    dist: trusty
    sudo: false
  - python: 3.7
    dist: xenia
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mojek
  password:
    secure: tmpzRriD61p+J85Ycz32EMsYw0HiZc5HjX60+1WdFV8YMVFJlMARRj4Ap2nC6dyj9ik9lpN6QKQyFr8QpGfzegXeySgC3EGpxiD93xQJ7oLF/pDncj3sAsLZYzo391IgHVvAPOSvs4FLeO9t6T5csTDi4iTEHx5eLMtKpal/UYTMf7ISupVtr724+/SVj1ay+tzkr2iKAeiQWg3q01nuVQLD5mNwkobau7MUuZTRiHg0QUdCvT6Faof91l1aAagyjeCptXr76AlU7u06gIdGF4Ibj4jlDeng2KzysFdrsPrCf6FTBk761/Spmhdji60CZd+LR/IbwXDboPTmWL2OJC183bglc0QQRx+P+0BzvBI0Z5WhZjtb9G4K6aBeSoMhkfX6LnytnHeBv9ZC8Dv1IESL4c2Kubj4kb8OqHSchxfgBDC8PtvouzjV/L2DRVxET6KVFbybZ9b7i9SAgJAkmz0Oa4JklT4rZy3vXsJYdXbQb0XXYW+PnZ3IbFPKQQosUUtJG7IFpgj2cppmTo34tkeHjrMWIiVqZOFb7wY2bgw/piGGMCU+MO8T4atI91qXGmWI4hy651mlMib+kzKBSqTR60t/WWQLPRAnhb0w+OOpnOGfj/oAvBwNrUBeoCM82ikNB+1K7/AAuAtrrBi9ZfXHZfk5w2Uq6mg0p87mNzo=
  on:
    tags: true
    repo: mojek/running_results_fetcher
    python: 3.7
after_success:
  - codecov  
