language: python
matrix:
  include:
  - python: 3.5
    dist: trusty
    sudo: false
  - python: 3.6
    dist: trusty
    sudo: false
  - python: 3.7
    dist: xenia
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mojek
  password:
    secure: eiOyO8/EEwEfzs2EuzqBCi+P7eNpqk7Kw47CIF1PzUbZD+NGa4eyRdG4FQ3nu4NVkJMGvgLbVYIVzDMDDTRLmn8JpPes4v/nLwXIKQrK56BpQSq+2UjOXpb5aElbdwEH+iU0bR/UOHCzbQUkexDlbne0/nmmKdvPiCaViZAVJPFI9+AwnWNH/pOgFBfAktsvGopwjtMbVeYyof+KpT6CToQK65G9NcAdzYyXGso+az5OGBbl+0dpI8aguqvbW3hKsPuxtiZPp6V4mVFvCkzQA5f06apyxKFk2qXr/AJEuT/W5rhp21gkyAzFyaR+67lN1VRs8J5TDnQ240nmlz+gX49KYElDgaNDD6sk5xd6PjMS3o8fngmfBuapNSy5UKPhmuo7070O04gJph2/bYZem5MG7S9bRdbGrErGmq0n3vbyQn6CAT+ogihkpyz6NXikKU/5XQlKMQV0UxKY3gYmE9WG53eVgPJWCqcsxnKgOxhsVIW81M2xaoMLJJ0A9ew4DV2Bf8jZgHB6WBTiXKAvOWHveQCH8S/IR4M88rI1BUfAKbEre1p6zl5W12Kl2NUv2M9f6nj7aQW6jhoAIs0c1Z+fiy7MF8XdK3WlHV7WuzfgHE3F4ywOjofl8xqMPBims4i2pusTTCA7XSunYlk8ULQnCa89U8iYpNHAR5EYpLY=
  on:
    tags: true
    repo: mojek/running_results_fetcher
    python: 3.7
after_success:
- pip install codecov &&  codecov
