language: python
matrix:
  include:
  - python: 3.5
    dist: trusty
    sudo: false
  - python: 3.6
    dist: trusty
    sudo: false
  - python: 3.7
    dist: xenia
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mojek
  password:
    secure: A+6fz6Edygeig1iCETjIeVThQceaU+v+1BfuRxpOECrOK4G7ePbHq173e0Qd05Kf/SjAFeiWw1UT1e7O5agLzX8VnexefPTd5qCO2mqjg0hVdagqno2JMDcm1TB36jRcjGuwAc7BZutYpuLt2AMX0vg7IK+IHEJECcQKNL9tcjiVfe4tYP0PKFOSVaT2tjwtb+fcmjvvl41zeyLE1agR0BSKmq/jFHuwUK6cAfIQZtVB7aGwqXs9nhP+AH8cYFMPwv36SfUUDgJOsMTz+Sq33ODjOJVxtzWrE/WRKl/r0aiHuw7tvpNG0rRZBQ1O7qsayD4uBAbt3oe1Q2dwjzLyA6HbuRedeUmUXuY44rcv25n6MqBIaE/celszI3xDHhc+hj86V6cU5bfSXFTcJM+uzDbCcBKB3Lyk4wK3eUd7twq6ZpShkqeRRgeTeK6BUDJou26cwSidUNnoGEiUvca8H+Gt7/RyIW7Vqm+Gd1JQeXsS3eGw5UtUmOT4OTW3du9iKuCGI2e5hea972OrYvFNO5F0HGm42XkHmkC7gz3e2BWI214i6YykBolsIwh8bhKsb3nmykAwqwDzGm3d0y9XGP+ulHIslgnFerdNHs31R0YVA5U9ntmZEXnQJj+7WRlhGQEUs6Y6hLWTrak6q2OvHtT7BPOD0pwOuRasuWOfdGk=
  on:
    tags: true
    repo: mojek/running_results_fetcher
    python: 3.7
after_success:
- pip install codecov &&  codecov
